language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-network cmake g++ libqt4-dev  libqt4-test qt4-dev-tools
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make
branches:
  only:
    - master
notifications:
  email:
    - daniel.agredano@brain-dynamics.es
