language: cpp
install:
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install --yes g++ cmake doxygen
script:
- mkdir build
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCUMENTATION=ON
- make
notifications:
  email:
    - daniel.agredano@brain-dynamics.es
