language: cpp
compiler:
  - clang
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt4-dev-tools g++ doxygen libqt4-dev libqt4-network libqt4-test
script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_DOCUMENTATION=ON
  - make
branches:
  only:
    - master
notifications:
  email:
    - daniel.agredano@brain-dynamics.es
