language: cpp
compiler:
  #- clang
  - gcc
before_install:
  - cat /etc/issue
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq qt4-dev-tools
before_script:
  - mkdir build
  - cd build
  - cmake ..
after_success:
  - make
branches:
  only:
    - master
notifications:
  email:
    - daniel.agredano@brain-dynamics.es
