sudo: false
language: cpp
cache:
  apt: true
  directories:
    - build
compiler:
  #- clang
  - gcc
before_install:
  - cat /etc/issue
  - add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - apt-get update -qq
  - apt-get install -qq cmake
  - apt-get install -qq qt4-dev-tools
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
branches:
  only:
    - master
notifications:
  email:
    - daniel.agredano@brain-dynamics.es
